baseurl: "/"
languageCode: "en-us"
title: "Songjhaha"
theme: ""
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; songjhaha 2017 -- {Year} | [Github](https://github.com/songjhaha)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
